Adding ability to run mhctools CLI with netMHCpan 4.0.
openvax/mhctools pull request #136
Opened 2018-06-22 05:52 UTC by julia326

Also: adding support for easily running with multiple versions of the same netMHC tool (same original binary name, optionally different versioned binary names made by the user) installed on one machine.

This lets us do things like:
```
mhctools --sequence SIINFEKL SIINFEKLQ --mhc-predictor netmhcpan3 --mhc-alleles A0201
```
vs
```
mhctools --sequence SIINFEKL SIINFEKLQ --mhc-predictor netmhcpan4 --mhc-alleles A0201
```
as well as the unversioned
```
mhctools --sequence SIINFEKL SIINFEKLQ --mhc-predictor netmhcpan --mhc-alleles A0201
```

2018-06-22 18:59 UTC, iskandr commented
How does this relate to the version sniffing in https://github.com/openvax/mhctools/blob/master/mhctools/netmhc_pan.py?

2018-06-22 19:07 UTC, iskandr requested changes
Since we already have version sniffing in the `NetMHCpan` and `NetMHC` functions I think that we should continue relying on those functions and just check whether the object they return is of the expected class. 

So, if a user specifies "netmhcpan4" this implies that you'll call `NetMHCpan(program_name="netMHCpan-4.0")` and if that fails, call `NetMHCpan(program_name="netmhcpan")`. The result of whichever of these calls succeeds is expected to be a NetMHCpan4 predictor object -- and an error is raised if the result is not of the correct type.

2018-06-22 19:07 UTC, iskandr commented on mhctools/cli/args.py
> -        "--mhc-epitope-lengths",
Dropping this argument?

2018-06-22 19:07 UTC, iskandr commented on mhctools/cli/args.py
> +    "netmhcpan28": ["netMHCpan-2.8", "netMHCpan"],
I think this will create pretty subtle bugs around creating a e.g. NetMHCpan28 predictor whose commandline predictor is actually 4.0

2018-06-25 18:27 UTC, julia326 commented on mhctools/cli/args.py
> -        "--mhc-epitope-lengths",
Yep, been deprecated for a little while and it's a bit confusing that it still exists

2018-12-11 02:48 UTC, iskandr commented
Just noticing this never got merged -- is MHCtools currently unable to use netmhcpan 4.0?

2020-09-08 18:47 UTC, iskandr commented
Closing for now

2020-09-08 18:47 UTC, closed without merging