Adding netmhcpan-3.0.
openvax/mhctools pull request #72
Opened 2016-11-11 16:46 UTC by julia326

2016-11-16 19:59 UTC, tavinathanson requested changes
Looks good, just a few comments/questions!

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/__init__.py
> +    "NetMHCpan2",
Maybe call this 2.8 to avoid confusing with e.g. older versions like 2.4?

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/file_formats.py
>          prediction_method_name="netmhcpan",
Call this `netmhcpan28`?

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/file_formats.py
> +        offset_index=4,
We talked about `offset` in `mhctools` being equal to `pos`, right? AFAIK this should break things. Does it? (If not, we should have tests to catch this?)

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_cons.py
> +            parse_output_fn=parse_netmhccons_stdout,
Thanks for fixing!

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_pan.py
> +    This function wraps NetMHCPan2 and NetMHCPan3 to automatically detect which class
Nit: `NetMHCpan2` and `NetMHCpan3` vs. `NetMHCPan2` and `NetMHCPan3`

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_pan.py
> +        program_name, "--version", "3",
Clarify here that "3" is meaningless?

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_pan.py
> +    	logger.info("Unknown version of netmhcpan, defaulting to 3.0")
Probably raise something here vs. continuing?

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_pan.py
> +    	logger.info("Unknown version of netmhcpan, defaulting to 3.0")
Nit: `NetMHCpan` is the correct capitalization of the tool

2016-11-16 19:59 UTC, tavinathanson commented on mhctools/netmhc_pan2.py
> +class NetMHCpan2(BaseCommandlinePredictor):
Same here, maybe call `NetMHCpan28`?

2016-11-16 19:59 UTC, tavinathanson commented on test/test_netmhc_pan.py
> -def test_netmhc_pan():
Where'd this go again?

2016-11-18 06:00 UTC, julia326 commented on mhctools/file_formats.py
> +        offset_index=4,
I have tests now, also specific to that field being correct in value - update coming up

2016-11-18 06:05 UTC, julia326 commented on test/test_netmhc_pan.py
> -def test_netmhc_pan():
Renamed the test file, but a later change made that rename unnecessary so will bring it back in the next commit

2016-11-18 20:29 UTC, tavinathanson commented on test/test_netmhc_pan.py
> +def test_netmhc_pan():
So this failed before your transform right?

2016-11-18 20:29 UTC, tavinathanson approved these changes
LGTM! I think it'd be great if you renamed `netmhc_pan2` to `28` as well for consistency but up to you

2016-11-18 22:42 UTC, julia326 commented on test/test_netmhc_pan.py
> +def test_netmhc_pan():
It did fail, in the expected way

2016-11-21 18:30 UTC, merged